- name: Install the Tomcat Application server to a server
  hosts: all
  remote_user: centos
  become: yes
  become_method: sudo
  tasks:
    - name: Ensure tomcat is installed
      yum:
        name: tomcat
        state: present
    - name: Ensure tomcat service is enabled and started
      service:
        name: tomcat
        enabled: yes
        state: started
      
